package com.liqy.douyin.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liqy.douyin.entity.User;
import com.liqy.douyin.entity.MusicType;
import com.liqy.douyin.entity.Music;

import com.liqy.douyin.db.UserDao;
import com.liqy.douyin.db.MusicTypeDao;
import com.liqy.douyin.db.MusicDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig musicTypeDaoConfig;
    private final DaoConfig musicDaoConfig;

    private final UserDao userDao;
    private final MusicTypeDao musicTypeDao;
    private final MusicDao musicDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        musicTypeDaoConfig = daoConfigMap.get(MusicTypeDao.class).clone();
        musicTypeDaoConfig.initIdentityScope(type);

        musicDaoConfig = daoConfigMap.get(MusicDao.class).clone();
        musicDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        musicTypeDao = new MusicTypeDao(musicTypeDaoConfig, this);
        musicDao = new MusicDao(musicDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(MusicType.class, musicTypeDao);
        registerDao(Music.class, musicDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        musicTypeDaoConfig.clearIdentityScope();
        musicDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MusicTypeDao getMusicTypeDao() {
        return musicTypeDao;
    }

    public MusicDao getMusicDao() {
        return musicDao;
    }

}
